# -*- coding: utf-8 -*-
"""시스템 설계안_for Anyone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLFrdhqdzsj8wOft5OMmbLlHJ05fqXV0

0. 필수 라이브러리 설치 및 시스템 설정
"""

# # 1. 필수 라이브러리 설치
# !pip install transformers torch scikit-learn biopython pandas numpy matplotlib

# # 2. 구글 드라이브 마운트
# from google.colab import drive
# import os
# drive.mount('/content/drive', force_remount=True)

#%%# 3. 작업 경로 설정
# drive_path = '/content/drive/MyDrive/Peptide_Project'
# if not os.path.exists(drive_path):
#     os.makedirs(drive_path)
#     print(f"✅ 경로 생성 완료: {drive_path}")

import os
# 현재 main.py 파일이 있는 폴더를 작업 기준점으로 잡습니다.
drive_path = os.path.dirname(os.path.abspath(__file__))

import matplotlib.pyplot as plt

# --- 윈도우/맥 공통 한글 폰트 설정 ---
if os.name == 'nt':  # Windows 환경
    plt.rc('font', family='Malgun Gothic') # 맑은 고딕
elif os.name == 'posix': # Mac 환경
    plt.rc('font', family='AppleGothic')
    
# 마이너스(-) 기호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

#%%# 4. Hugging Face 인증 (Secrets에 HF_TOKEN을 등록했다면 자동 연동됩니다)
# # 토큰은 TOKEN 파일에 있습니다.
# try:
#     from google.colab import userdata
#     os.environ["HF_TOKEN"] = userdata.get('HF_TOKEN')
#     print("✅ Hugging Face 토큰 인증 성공!")
# except:
#     print("⚠️ 경고: HF_TOKEN이 없습니다. 익명 모드로 진행하여 속도가 제한될 수 있습니다.")
    
import os
from dotenv import load_dotenv
from huggingface_hub import login
import warnings

# Hugging Face 심볼릭 링크 경고 끄기
os.environ['HF_HUB_DISABLE_SYMLINKS_WARNING'] = '1'

# 기타 자잘한 경고 숨기기 (선택 사항)
warnings.filterwarnings('ignore')

# 1. .env 파일에서 환경 변수 불러오기
load_dotenv()

# 2. HF_TOKEN 가져오기
hf_token = os.getenv("HF_TOKEN")

# 3. 토큰이 잘 불러와졌는지 확인 후 로그인
if hf_token:
    print("✅ Hugging Face 토큰을 성공적으로 불러왔습니다.")
    login(token=hf_token)
else:
    print("⚠️ 경고: .env 파일에서 HF_TOKEN을 찾을 수 없습니다!")

#%%"""1. User_input setting json 설정 (input 파트)"""

system_config = {
    "data_params": {
        "dataset_path": f"{drive_path}/peptide_dataset_5_50.csv",
        "sample_size": 60000,
        "max_len": 50
    },
    "weights": {
        "w_1_ai": 1.0,      # 최우선 목표: 면역 거부 반응 최소화
        "w_2_gravy": 0.5,   # 제약: 친소수성 안전지대 지정 (-0.4 ~ 0.4)
        "w_3_charge": 0.5,  # 제약: 전하량 안전지대 지정 (-1.0 ~ 1.0)
        "w_4_cd47": 0.4     # 전략: CD47의 면역 회피 모티프를 갖고 있을 시 보너스 부여
    },
    "algorithm_params": {
        "ga_generations": 30,
        "ga_pop_size": 100,
        "mutation_rate": 0.3,
        "indel_rate": 0.3,         # Indel 변이(삽입/삭제) 발생 비율 (변이 발생 시 이 확률로 Indel 선택)
        "ga_max_len": 15,           # GA 펩타이드 최대 길이 제한
        "checkpoint_interval": 10,  # N세대마다 GA 진화 상태 체크포인트 저장
        "n_runs_bench": 3           # Ablation Study 반복 횟수
    },
    "design_constraints": {
        "hCD47_reference": "EVTELT" # CD47의 면역 회피 모티프
    }
}

#%%"""2. 데이터 로드 및 일괄 전처리 단계"""

import torch
import pandas as pd
import numpy as np
from transformers import EsmTokenizer
from Bio.Align import substitution_matrices
from torch.utils.data import TensorDataset, DataLoader

def prepare_data(config):
    print("📊 데이터 로딩 및 일괄 전처리 시작...")
    df = pd.read_csv(config["data_params"]["dataset_path"]).dropna(subset=['Sequence', 'Target'])
    if len(df) > config["data_params"]["sample_size"]:
        df = df.sample(n=config["data_params"]["sample_size"], random_state=42)

    sequences = df['Sequence'].tolist()
    labels = torch.tensor(df['Target'].values, dtype=torch.float32)

    # 1. BLOSUM62 Embedding
    # BLOSUM62 = 생물학적 관계도를 숫자로 바꾼 사전
    # BLOSUM62를 이용해서 아미노산 서열을 AI가 이해할 수 있도록 정리하는 과정

    blosum62 = substitution_matrices.load("BLOSUM62")
    aa_order = "ARNDCQEGHILKMFPSTWYV"
    aa_to_idx = {aa: i for i, aa in enumerate(aa_order)}

    max_len = config["data_params"]["max_len"]
    blosum_tensors = np.zeros((len(sequences), max_len, 20), dtype=np.float32)
    for idx, seq in enumerate(sequences):
        start_idx = max(0, max_len - len(seq))
        for i, aa in enumerate(seq[-max_len:]):
            if aa in aa_to_idx:
                for j, ref_aa in enumerate(aa_order):
                    blosum_tensors[idx, start_idx + i, j] = blosum62.get((aa, ref_aa), -1)

    # 2. ESM-2 Tokenization
    # ESM-2 = 이미 엄청난 양의 데이터를 학습한 모델
    # ESM-2에 바로 들어갈 수 있도록 데이터 전체를 미리 토큰화해서 작업 속도를 높인 과정

    tokenizer = EsmTokenizer.from_pretrained("facebook/esm2_t6_8M_UR50D")
    esm_encodings = tokenizer(sequences, padding='max_length', max_length=max_len+2, truncation=True, return_tensors="pt")

    print("✅ 데이터 변환 완료!")
    return TensorDataset(torch.tensor(blosum_tensors), esm_encodings['input_ids'], esm_encodings['attention_mask'], labels), aa_to_idx

dataset, aa_idx = prepare_data(system_config)

#%%"""3. AI 모델들을 정의하는 단계 (pipeline A 시작부)"""

import torch.nn as nn
import torch.nn.functional as F
from transformers import EsmModel

# 모델1: 1D-CNN
class CNNOnly(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn = nn.Conv1d(20, 64, kernel_size=3, padding=1)
        self.fc = nn.Linear(64, 1)
    def forward(self, blosum, ids, mask):
        x = F.relu(self.cnn(blosum.permute(0, 2, 1)))
        return torch.sigmoid(self.fc(F.max_pool1d(x, x.size(2)).squeeze(2)))

# 모델2: Bi-LSTM
class LSTMOnly(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(20, 64, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(128, 1)
    def forward(self, blosum, ids, mask):
        out, _ = self.lstm(blosum)
        return torch.sigmoid(self.fc(out[:, -1, :]))

# 모델3: 직렬 형식의 hybrid model
# 1D-CNN -> Max-Pooling -> Bi-LSTM으로 연결된 model로, 프로젝트에서 메인이 되는 모델
# 1D-CNN: 독성이 있는 부위를 뽑아내는 역할
# Bi-LSTM: 맥락을 읽고 판단하는 역할
class SeqHybrid(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn = nn.Conv1d(20, 64, kernel_size=3, padding=1)
        self.lstm = nn.LSTM(64, 64, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(128, 1)
    def forward(self, blosum, ids, mask):
        x = F.relu(self.cnn(blosum.permute(0, 2, 1)))
        out, _ = self.lstm(F.max_pool1d(x, 2).permute(0, 2, 1))
        return torch.sigmoid(self.fc(out[:, -1, :]))

# 모델4: 병렬 형식의 hybrid model
# 직렬로 해야하는 이유를 보여주기 위함
# 데이터가 두 모델에 각각 들어가서 나온 feature들을 late fusion으로 결합하는 방식
class ParallelHybrid(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn = nn.Conv1d(20, 64, kernel_size=3, padding=1)
        self.lstm = nn.LSTM(20, 64, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(64 + 128, 1)
    def forward(self, blosum, ids, mask):
        x_c = F.max_pool1d(F.relu(self.cnn(blosum.permute(0, 2, 1))), 50).squeeze(2)
        out, _ = self.lstm(blosum)
        return torch.sigmoid(self.fc(torch.cat((x_c, out[:, -1, :]), dim=1)))

# 모델5: ESM-2
# 기존에 이미 많은 데이터를 학습한 모델로 하면 되는 거 아닌가를 확인하기 위함.
class ESM2Only(nn.Module):
    def __init__(self):
        super().__init__()
        self.esm2 = EsmModel.from_pretrained("facebook/esm2_t6_8M_UR50D")
        for p in self.esm2.parameters(): p.requires_grad = False
        self.fc = nn.Linear(320, 1)
    def forward(self, blosum, ids, mask):
        out = self.esm2(input_ids=ids, attention_mask=mask)
        return torch.sigmoid(self.fc(out.last_hidden_state[:, 0, :]))

# 모델6: main(seq hybrid) + auxiliary(ESM-2)
# 메인 모델에 ESM-2를 통한 보조를 통해 결과가 더 좋아질 수 있는지 확인하기 위함.
class MainAuxHybrid(nn.Module):
    def __init__(self):
        super().__init__()
        self.main_cnn = nn.Conv1d(20, 32, kernel_size=3, padding=1)
        self.main_lstm = nn.LSTM(32, 32, batch_first=True, bidirectional=True)
        self.esm2 = EsmModel.from_pretrained("facebook/esm2_t6_8M_UR50D")
        for p in self.esm2.parameters(): p.requires_grad = False
        self.fc = nn.Linear(64 + 320, 1)
    def forward(self, blosum, ids, mask):
        x_m = F.max_pool1d(F.relu(self.main_cnn(blosum.permute(0, 2, 1))), 2).permute(0, 2, 1)
        out, _ = self.main_lstm(x_m)
        esm_out = self.esm2(input_ids=ids, attention_mask=mask)
        return torch.sigmoid(self.fc(torch.cat((out[:, -1, :], esm_out.last_hidden_state[:, 0, :]), dim=1)))

# max-pooling의 여부에 따른 성능의 차이를 비교하기 위한 모델들

# 모델7: max-pooling이 없는 직렬 형식의 hybrid 모델
class SeqHybridNoPool(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn = nn.Conv1d(20, 64, kernel_size=3, padding=1)
        self.lstm = nn.LSTM(64, 64, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(128, 1)
    def forward(self, blosum, ids, mask):
        x = F.relu(self.cnn(blosum.permute(0, 2, 1)))
        # Max Pooling 제거: CNN의 출력을 바로 모양만 바꿔서(길이 유지) LSTM에 전달!
        out, _ = self.lstm(x.permute(0, 2, 1))
        return torch.sigmoid(self.fc(out[:, -1, :]))

#모델8: max-pooling이 없는 병렬 형식의 seq hybrid 모델
class ParallelHybridNoPool(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn = nn.Conv1d(20, 64, kernel_size=3, padding=1)
        self.lstm = nn.LSTM(20, 64, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(64 + 128, 1)
    def forward(self, blosum, ids, mask):
        x = F.relu(self.cnn(blosum.permute(0, 2, 1)))
        # Max Pooling 제거: CNN 전체 출력의 평균을 내서(Global Average) 정보를 보존해봄
        x_c = torch.mean(x, dim=2)
        out, _ = self.lstm(blosum)
        return torch.sigmoid(self.fc(torch.cat((x_c, out[:, -1, :]), dim=1)))

'''
모델 1~8을 비교한 결과, ESM-2를 적용하는 부분은 역효과를 냈으며, max-pooling 또한 결과에 좋은 영향을 주지 못했음.

1D-CNN 단독 모델과 병렬 형식의 모델은 성능이 좋지 않았음.

다만, Bi-LSTM의 성능이 seq hybrid 보다 좋은 결과를 도출한 것을 통해 seq hybrid에 문제가 있는지를 확인이 필요함.

문제는 Cascading Errors로 확인됐으며, 아래의 보완 방식을 각각 적용하여 보완해보기로 함.

1. Residual Connection / Skip Connection
2. Attention Mechanism

(메일 송신 이후 추가 내용)

이후 sample_size를 20000에서 60000으로 변경하고, 
in silico 특성상 시간보다 메모리 사용량의 영향이 큰 것을 반영한 결과
seq hybrid (pool) model이 선정되었음.
즉, 문제는 sample_size가 너무 작아서 생긴 문제임을 확인함.

이를 검증할 때, 
10개 모델 비교시 1회 run에 최대 1680초, 즉 28분 이상이 걸린 ESM-2 계열 모델들을
시관 관계상 제외하고 진행함.
(매 시도마다 ESM-2 계열 모델들이 독보적으로 시간이 많이 걸렸기 때문)
그래서, 이후 트래킹용 딕셔너리를 만들 때 해당 모델들을 주석 처리했음.

'''

# 🔥 1. 잔차 연결 (Residual Connection) 적용 모델 🔥
class SeqHybridResidual(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn = nn.Conv1d(20, 64, kernel_size=3, padding=1)
        # 원본(20) + CNN요약본(64) = 84 차원의 데이터를 LSTM이 받음
        self.lstm = nn.LSTM(84, 64, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(128, 1)

    def forward(self, blosum, ids, mask):
        x_cnn = F.relu(self.cnn(blosum.permute(0, 2, 1))) # (B, 64, L)
        # 지름길: CNN 요약본과 원본 블로섬 데이터를 결합 (Concat)
        x_combined = torch.cat((blosum.permute(0, 2, 1), x_cnn), dim=1) # (B, 84, L)
        out, _ = self.lstm(x_combined.permute(0, 2, 1))
        return torch.sigmoid(self.fc(out[:, -1, :]))

# 🔥 2. 어텐션 매커니즘 (Attention Mechanism) 적용 모델 🔥
class SeqHybridAttention(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn = nn.Conv1d(20, 64, kernel_size=3, padding=1)
        self.lstm = nn.LSTM(64, 64, batch_first=True, bidirectional=True)
        # 각 아미노산 위치에 매길 가중치(형광펜)를 학습하는 층
        self.attention = nn.Linear(128, 1)
        self.fc = nn.Linear(128, 1)

    def forward(self, blosum, ids, mask):
        x = F.relu(self.cnn(blosum.permute(0, 2, 1)))
        out, _ = self.lstm(x.permute(0, 2, 1)) # out shape: (B, L, 128)

        # 어텐션 스코어 계산 (어떤 아미노산이 중요한가?)
        attn_weights = F.softmax(self.attention(out), dim=1) # shape: (B, L, 1)

        # 중요도에 따라 전체 문맥 벡터를 하나로 응축 (Weighted Sum)
        context_vector = torch.sum(attn_weights * out, dim=1) # shape: (B, 128)
        return torch.sigmoid(self.fc(context_vector))

#%%
"""4. 모델간 비교 실험 (Ablation study) 및 체크포인트 저장

---
1. 각 모델은 동일한 epoch(30)로 학습
2. 시행은 총 3번 진행하며, 3회의 결과값의 평균값을 구하여 모델 간 비교한다.
3. 결과값은 각 시행마다 Validation Loss가 가장 낮았던 최적의 Epoch의 값으로 한다.
4. 결과값으로 사용하는 것은 'AUROC의 평균', '평균 학습시간', 'peak memory usage'이다.

"""

import time
import tracemalloc
from sklearn.metrics import roc_auc_score

# 🔥 누락된 device 설정 추가! 🔥
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"🖥️ 현재 사용 중인 디바이스: {device}")

# -------------------------------------------------------------------
# 트래킹용 전역 딕셔너리 생성
# -------------------------------------------------------------------
# 구조: history[model_name] = {'auroc_history': [[epoch1...15], [epoch1...15], [epoch1...15]], 'times': [], 'memories': []}
model_history = {}

def run_benchmarking_v_final(dataset, config):
    models = {
        # 단독 모델 (비교군)
        "1D-CNN Only": CNNOnly,
        "Bi-LSTM Only": LSTMOnly,
        # 직렬 연결 방식의 모델 (목표 모델), max-pooling 포함/미포함
        "Seq Hybrid (Pool)": SeqHybrid,
        "Seq Hybrid (No Pool)": SeqHybridNoPool,
        # 병렬 연결 방식의 모델 (비교군), max-pooling 포함/미포함
        "Parallel Hybrid (Pool)": ParallelHybrid,
        "Parallel Hybrid (No Pool)": ParallelHybridNoPool,
        # # # ESM-2를 접목한 모델 (test용 모델)
        # "ESM-2 Only": ESM2Only,
        # "Main-Aux Hybrid": MainAuxHybrid,
        # 🌟 새롭게 참전하는 모델 2종 🌟
        # "Seq Hybrid (Residual)": SeqHybridResidual,
        # "Seq Hybrid (Attention)": SeqHybridAttention,
    }

    results = []
    print(f"\n🚀 {config['algorithm_params']['n_runs_bench']}-Run Benchmarking Started...\n")

    for name, model_class in models.items():
        print(f"▶ Training [{name}]...")
        model_history[name] = {'auroc_history': [], 'times': [], 'memories': [], 'best_epochs': []}

        run_aurocs = []

        for run in range(config["algorithm_params"]["n_runs_bench"]):
            torch.manual_seed(run)
            model = model_class().to(device)
            optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.001)

            train_set, val_set = torch.utils.data.random_split(dataset, [16000, len(dataset)-16000])
            train_loader = DataLoader(train_set, batch_size=128, shuffle=True)
            val_loader = DataLoader(val_set, batch_size=128)

            best_val_loss = float('inf')
            save_path = f"{drive_path}/best_{name.replace(' ', '_')}.pth"

            # --- 트래킹 변수 ---
            run_epoch_aurocs = []
            best_ep = 0

            tracemalloc.start()
            start_time = time.time()

            # Epoch 루프
            for epoch in range(30):
                model.train()
                for b, i, m, l in train_loader:
                    optimizer.zero_grad()
                    loss = F.binary_cross_entropy(model(b.to(device), i.to(device), m.to(device)).squeeze(), l.to(device))
                    loss.backward()
                    optimizer.step()

                model.eval()
                v_loss = 0
                all_p, all_l = [], []
                with torch.no_grad():
                    for b, i, m, l in val_loader:
                        preds = model(b.to(device), i.to(device), m.to(device)).squeeze()
                        v_loss += F.binary_cross_entropy(preds, l.to(device)).item()
                        all_p.extend(preds.cpu().numpy())
                        all_l.extend(l.numpy())

                # Checkpointing
                if v_loss < best_val_loss:
                    best_val_loss = v_loss
                    best_ep = epoch + 1
                    torch.save(model.state_dict(), save_path)

                # 매 에포크마다 AUROC 기록 (그래프용)
                run_epoch_aurocs.append(roc_auc_score(all_l, all_p))

            # 기록 저장
            run_time = time.time() - start_time
            _, peak_mem = tracemalloc.get_traced_memory()
            tracemalloc.stop()

            model_history[name]['auroc_history'].append(run_epoch_aurocs)
            model_history[name]['times'].append(run_time)
            model_history[name]['memories'].append(peak_mem / 10**6) # MB 변환
            model_history[name]['best_epochs'].append(best_ep)

            # 런 최종 성능은 황금기(Checkpoint) 모델 로드하여 산출
            model.load_state_dict(torch.load(save_path))
            model.eval()
            all_p_final, all_l_final = [], []
            with torch.no_grad():
                for b, i, m, l in val_loader:
                    all_p_final.extend(model(b.to(device), i.to(device), m.to(device)).squeeze().cpu().numpy())
                    all_l_final.extend(l.numpy())
            run_aurocs.append(roc_auc_score(all_l_final, all_p_final))

        # N-Run 통계 수합
        avg_auroc = np.mean(run_aurocs)
        std_auroc = np.std(run_aurocs)
        avg_time = np.mean(model_history[name]['times'])

        results.append({
            "Model": name,
            "Mean_AUROC": avg_auroc,
            "Std_AUROC": std_auroc,
            "Mean_Time": avg_time,
            "Peak_Mem_MB": np.mean(model_history[name]['memories'])
        })

    return pd.DataFrame(results)

df_report = run_benchmarking_v_final(dataset, system_config)
print(df_report)

# 벤치마킹 결과를 CSV로 저장 → pipeline_b_only.py에서 최적 모델 자동 선정에 사용
_bench_csv_path = os.path.join(drive_path, "benchmark_report.csv")
df_report.to_csv(_bench_csv_path, index=False)
print(f"💾 벤치마킹 결과 저장 완료 → {_bench_csv_path}")

#%%"""5. 비교 실험 결과 시각화 (차이가 큰 부분이 있어 일부 구간 생략)"""

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import os
from datetime import datetime

def plot_benchmark_results_grouped(history_dict, df):
    # 우측 메모리 그래프가 3층으로 쌓일 것을 대비해 세로 길이를 9로 충분히 늘려줍니다.
    fig = plt.figure(figsize=(24, 9)) 
    
    # 1행 3열의 큰 뼈대 생성
    gs0 = gridspec.GridSpec(1, 3, figure=fig, wspace=0.25, bottom=0.15)
    
    models = list(history_dict.keys())

    # -------------------------------------------------------------
    # 1. AUROC per Epoch Graph (좌측 - 건드리지 않음)
    # -------------------------------------------------------------
    ax1 = fig.add_subplot(gs0[0]) 
    for model_name in models:
        hist_array = np.array(history_dict[model_name]['auroc_history'])
        mean_auroc = np.mean(hist_array, axis=0)
        std_auroc = np.std(hist_array, axis=0)
        
        epochs = np.arange(1, len(mean_auroc) + 1) 
        
        line, = ax1.plot(epochs, mean_auroc, label=model_name, marker='o', markersize=3)
        ax1.fill_between(epochs, mean_auroc - std_auroc, mean_auroc + std_auroc, alpha=0.1)
        
        best_ep = np.argmax(mean_auroc)
        ax1.scatter(epochs[best_ep], mean_auroc[best_ep], color=line.get_color(), s=80, edgecolors='black', zorder=5)

    ax1.set_title("Validation AUROC by Epoch", fontsize=14)
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("AUROC")
    ax1.legend(fontsize=9, loc='lower right', ncol=2) 
    ax1.grid(True, linestyle='--', alpha=0.6)

    # -------------------------------------------------------------
    # 2. Training Time Plot (가운데 - 🔥 동적 절취선 패치 🔥)
    # -------------------------------------------------------------
    gs_time = gridspec.GridSpecFromSubplotSpec(2, 1, subplot_spec=gs0[1], height_ratios=[1, 2], hspace=0.15)
    ax2_top = fig.add_subplot(gs_time[0])
    ax2_bot = fig.add_subplot(gs_time[1], sharex=ax2_top)

    means = df['Mean_Time'].values
    stds = [np.std(history_dict[m]['times']) for m in models]
    
    # 🔥 해결책: 100초 고정이 아니라, 모델들 중 'ESM'이 들어간 무거운 모델들을 기준으로 분리합니다.
    # ESM 모델은 압도적으로 느리므로 이를 위쪽 그래프로, 나머지를 아래쪽 그래프로 보냅니다.
    high_vals = []
    low_vals = []
    
    for i, m in enumerate(models):
        val_plus = means[i] + stds[i]
        val_minus = means[i] - stds[i]
        if "ESM" in m or "Main-Aux" in m:  # ESM이나 Main-Aux 하이브리드는 무조건 느림
            high_vals.extend([val_plus, val_minus])
        else:
            low_vals.extend([val_plus, val_minus])
            
    # 만약 모든 모델이 다 빠르거나 다 느려서 한쪽에 몰려있다면, 에러 방지를 위해 기본값 부여
    if not low_vals: low_vals = [0, max(high_vals) * 0.5]
    if not high_vals: high_vals = [max(low_vals) * 1.5, max(low_vals) * 2.0]
    
    x_pos = np.arange(len(models))
    ax2_top.errorbar(x_pos, means, yerr=stds, fmt='o', capsize=5, capthick=2, ecolor='black', color='blue', markersize=8)
    ax2_bot.errorbar(x_pos, means, yerr=stds, fmt='o', capsize=5, capthick=2, ecolor='black', color='blue', markersize=8)

    ax2_bot.set_ylim(max(0, min(low_vals) * 0.9), max(low_vals) * 1.1)
    ax2_top.set_ylim(min(high_vals) * 0.9, max(high_vals) * 1.1)

    ax2_top.spines['bottom'].set_visible(False)
    ax2_bot.spines['top'].set_visible(False)
    ax2_top.tick_params(labelbottom=False, bottom=False)

    d = .015 
    kwargs = dict(transform=ax2_top.transAxes, color='k', clip_on=False)
    ax2_top.plot((-d, +d), (-d, +d), **kwargs); ax2_top.plot((1 - d, 1 + d), (-d, +d), **kwargs)        
    kwargs.update(transform=ax2_bot.transAxes)  
    ax2_bot.plot((-d, +d), (1 - d, 1 + d), **kwargs); ax2_bot.plot((1 - d, 1 + d), (1 - d, 1 + d), **kwargs)  

    ax2_top.set_title("Training Time per Model (Broken Axis)", fontsize=14)
    ax2_bot.set_ylabel("Time (s)")
    ax2_bot.set_xticks(x_pos)
    ax2_bot.set_xticklabels(models, rotation=45, ha='right', fontsize=11)
    ax2_top.grid(axis='y', linestyle='--', alpha=0.6)
    ax2_bot.grid(axis='y', linestyle='--', alpha=0.6)

    # -------------------------------------------------------------
    # 3. Peak Memory Box Plot (우측 - 건드리지 않음)
    # -------------------------------------------------------------
    mem_means = [np.mean(history_dict[m]['memories']) for m in models]
    
    groups = {
        'Group A (Outliers: > 10MB)': [], 
        'Group B (Heavy: 1.3 ~ 10MB)': [], 
        'Group C (Standard: < 1.3MB)': []
    }
    
    for m, val in zip(models, mem_means):
        if val > 10:
            groups['Group A (Outliers: > 10MB)'].append(m)
        elif val > 1.3:
            groups['Group B (Heavy: 1.3 ~ 10MB)'].append(m)
        else:
            groups['Group C (Standard: < 1.3MB)'].append(m)
            
    active_groups = {k: v for k, v in groups.items() if len(v) > 0}
    num_groups = len(active_groups)
    
    gs_mem = gridspec.GridSpecFromSubplotSpec(num_groups, 1, subplot_spec=gs0[2], hspace=0.7)
    
    for i, (g_name, g_models) in enumerate(active_groups.items()):
        ax3 = fig.add_subplot(gs_mem[i])
        g_data = [history_dict[m]['memories'] for m in g_models]
        
        ax3.boxplot(g_data, patch_artist=True)
        ax3.set_title(g_name, fontsize=12, fontweight='bold', color='darkred' if i==0 else 'black')
        ax3.set_ylabel("Memory (MB)")
        
        ax3.set_xticks(range(1, len(g_models) + 1))
        ax3.set_xticklabels(g_models, rotation=25, ha='right', fontsize=10) 
        ax3.grid(axis='y', linestyle='--', alpha=0.6)

    fig.align_labels()
    
    try:
        figure_time = datetime.now().strftime('%y%m%d_%H%M%S')
        save_path = os.path.join(drive_path, f"benchmark_results_grouped_final_{figure_time}.png")
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"✅ 그래프가 저장되었습니다: {save_path}")
    except Exception as e:
        print(f"⚠️ 이미지 저장 실패: {e}")

    plt.show()

# 함수 실행
plot_benchmark_results_grouped(model_history, df_report)

#%%
"""6. 최적 모델 선정 (pipeline A 종료부)


---
선정 기준
1. 최적 epoch에서의 AUROC의 값이 높을 것
2. 학습에 걸린 시간과 메모리 사용량이 작고 편차가 적을 것
3. 단, in silico 환경이므로, 시간보다는 메모리 사용량을 더 비중있게 볼 것 (메일 송신 이후 추가)
"""

print("🔍 Analyzing Benchmark Results using Multi-Objective Optimization...")

# 1. 통합 점수 가중치 설정
# 각 지표를 모델 간 Min-Max 정규화(0~1)한 뒤 가중치를 곱하여
# 지표별 실제 값 범위 차이에 관계없이 가중치가 의도한 중요도를 그대로 반영함.
# (예: AUROC 범위 0.70~0.74 vs Memory 범위 6.32~6.37 → 정규화 전에는 Memory 페널티가 사실상 상수로 작용)
W_AUROC = 1.0   # 모델 성능 (높을수록 좋음 → +)
W_STD   = 0.1   # 성능 안정성 (낮을수록 좋음 → -)
W_TIME  = 0.1   # 학습 시간 (낮을수록 좋음 → -, in silico이므로 메모리보다 낮은 비중)
W_MEM   = 0.3   # 메모리 사용량 (낮을수록 좋음 → -)

# 2. 각 지표를 모델 간 Min-Max 정규화 (0~1, 분모가 0이 되는 경우 1e-9로 보호)
eps = 1e-9
auroc_norm = (df_report['Mean_AUROC']  - df_report['Mean_AUROC'].min())  / (df_report['Mean_AUROC'].max()  - df_report['Mean_AUROC'].min()  + eps)
std_norm   = (df_report['Std_AUROC']   - df_report['Std_AUROC'].min())   / (df_report['Std_AUROC'].max()   - df_report['Std_AUROC'].min()   + eps)
time_norm  = (df_report['Mean_Time']   - df_report['Mean_Time'].min())   / (df_report['Mean_Time'].max()   - df_report['Mean_Time'].min()   + eps)
mem_norm   = (df_report['Peak_Mem_MB'] - df_report['Peak_Mem_MB'].min()) / (df_report['Peak_Mem_MB'].max() - df_report['Peak_Mem_MB'].min() + eps)

# 3. 통합 점수(Total Score) 산출
df_report['Total_Score'] = (
      W_AUROC * auroc_norm
    - W_STD   * std_norm
    - W_TIME  * time_norm
    - W_MEM   * mem_norm
)

# 3. 1등 모델 판별 및 가중치 로드 (에러 수정 완료)
df_sorted = df_report.sort_values(by='Total_Score', ascending=False)
best_model_row = df_sorted.iloc[0]
best_model_name = best_model_row['Model']

print(f"\n🏆 최종 최적 모델 (Best Model Selected): [{best_model_name}]")
print(f"  - 통합 점수 (Total Score): {best_model_row['Total_Score']:.4f}")
print(f"  - 성능 지표 (AUROC) : {best_model_row['Mean_AUROC']:.4f} (±{best_model_row['Std_AUROC']:.4f})")
print(f"  - 연산 비용 (Time)  : {best_model_row['Mean_Time']:.1f} sec")
print(f"  - 메모리 (Memory)   : {best_model_row['Peak_Mem_MB']:.2f} MB\n")

# 전체 순위표 출력
print("📊 [모델별 최종 통합 점수 순위]")
print(df_sorted[['Model', 'Total_Score', 'Mean_AUROC', 'Mean_Time', 'Peak_Mem_MB']].to_string(index=False))

# 🔥 10가지 모든 모델 아키텍처가 완벽히 연결된 매핑 딕셔너리
model_mapping = {
    "1D-CNN Only": CNNOnly, 
    "Bi-LSTM Only": LSTMOnly, 
    "Seq Hybrid (Pool)": SeqHybrid, 
    "Seq Hybrid (No Pool)": SeqHybridNoPool,
    "Parallel Hybrid (Pool)": ParallelHybrid, 
    "Parallel Hybrid (No Pool)": ParallelHybridNoPool,
    "Seq Hybrid (Residual)": SeqHybridResidual,
    "Seq Hybrid (Attention)": SeqHybridAttention,
    "ESM-2 Only": ESM2Only, 
    "Main-Aux Hybrid": MainAuxHybrid
}

# 선택된 최고의 심사위원(Best Model) 클래스 인스턴스화 및 저장된 가중치 로드
best_model = model_mapping[best_model_name]().to(device)
best_model.load_state_dict(torch.load(f"{drive_path}/best_{best_model_name.replace(' ', '_')}.pth"))
print(f"✅ 최고의 심사위원 [{best_model_name}] 등용 완료 및 가중치 로드 성공!")
#%%
"""7. Pipeline B: 유전 알고리즘 (적응형 돌연변이 & 추적 엔진 통합)

---
유전 알고리즘 방식
1. 무작위로 100개의 펩타이드 서열을 만든다.
2. 최적 모델이 점수를 매겨 가장 안전하고 물성이 좋은 상위 20%만 남긴다.
3. 남은 것들끼리 일부를 교차하거나, 서열의 일부 길이가 늘어나거나 줄어드는 돌연변이가 발생한다.
4. 위 과정을 30~50세대 반복하여 결과물을 도출한다.
"""

import random
import copy
import json
import torch
import torch.nn as nn
from Bio.SeqUtils.ProtParam import ProteinAnalysis
import matplotlib.pyplot as plt
import os

print("\n🚀 [Pipeline B] 적응형 유전 알고리즘 기반 면역 회피 펩타이드 역설계 가동...")

# 임베딩 레이어 안전 로드 (Scope 에러 방지)
def get_safe_embed_layer():
    blosum62 = substitution_matrices.load("BLOSUM62")
    aa_list = list("ACDEFGHIKLMNPQRSTVWY")
    aa_idx_map = {aa: i + 1 for i, aa in enumerate(aa_list)}
    aa_idx_map['PAD'] = 0
    embed_dim_size = len(aa_list)
    embedding_matrix = torch.zeros((len(aa_idx_map), embed_dim_size))
    for aa1 in aa_list:
        for aa2 in aa_list:
            score = blosum62[aa1, aa2] if (aa1, aa2) in blosum62 else blosum62[aa2, aa1]
            embedding_matrix[aa_idx_map[aa1], aa_idx_map[aa2] - 1] = score
    emb_layer = nn.Embedding.from_pretrained(embedding_matrix, freeze=True)
    return emb_layer, aa_idx_map

embed_layer_main, aa_idx_main = get_safe_embed_layer()
embed_layer_main = embed_layer_main.to(device)


# 🔥 메인 엔진: 통합 run_pipeline_B 함수 🔥
def run_pipeline_B(model, aa_to_idx, embed_layer, config):
    algo_params = config.get("algorithm_params", {})
    pop_size = algo_params.get("ga_population_size", algo_params.get("population_size", 50))
    generations = algo_params.get("ga_generations", algo_params.get("generations", 30))
    indel_rate = algo_params.get("indel_rate", 0.3)
    ga_max_len = algo_params.get("ga_max_len", 15)
    checkpoint_interval = algo_params.get("checkpoint_interval", 10)
    constraints = config.get("design_constraints", {})
    ref = constraints.get("hCD47_reference", constraints.get("reference_motif", "EVTELT"))
    ga_min_len = len(ref)  # 참조 모티프 길이를 최소 서열 길이로 사용
    
    # 세대별 궤적 기록 장부
    history = {
        'gen': [], 'best_cost': [], 'mean_cost': [],
        'p_fbr': [], 'diversity': [], 'mutation_rate': [],
        'indel_count': []
    }
    
    # 초기 개체군 생성
    pop = [("".join(random.choices("ACDEFGHIKLMNPQRSTVWY", k=max(0, random.randint(0, ga_max_len - len(ref))))) +
            ref +
            "".join(random.choices("ACDEFGHIKLMNPQRSTVWY", k=max(0, random.randint(0, ga_max_len - len(ref))))))[:ga_max_len]
           for _ in range(pop_size)]
    
    model.to(device)
    model.eval()
    
    base_mutation_rate = 0.10 
    current_mutation_rate = base_mutation_rate
    
    for gen in range(generations):
        scored_pop = []
        for seq in pop:
            pad_len = 15 - len(seq)
            pad = ['PAD'] * pad_len + list(seq)
            with torch.no_grad():
                idx_tensor = torch.tensor([[aa_to_idx.get(aa, 0) for aa in pad]], dtype=torch.long).to(device)
                embedded_tensor = embed_layer(idx_tensor) 
                dummy_ids = torch.zeros_like(idx_tensor).to(device) 
                dummy_mask = torch.tensor([[0]*pad_len + [1]*len(seq)], dtype=torch.long).to(device)
                try:
                    p_fbr = model(embedded_tensor, dummy_ids, dummy_mask).item()
                except TypeError:
                    p_fbr = model(embedded_tensor).item()
            
            analysis = ProteinAnalysis(seq)
            gravy, charge = analysis.gravy(), analysis.charge_at_pH(7.4)
            h_score = sum(1 for a, b in zip(seq, ref) if a == b) if ref in seq else 0.0
            
            w = config.get("weights", {})
            w_ai = w.get("w_1_ai", w.get("p_fbr", 0.5))
            w_gr = w.get("w_2_gravy", w.get("gravy", 0.15))
            w_ch = w.get("w_3_charge", w.get("charge", 0.15))
            w_cd = w.get("w_4_cd47", w.get("hcd47", 0.2))

            # 각 항을 정의된 물리적 범위로 정규화하여 가중치가 실제 중요도를 반영하도록 함.
            # 정규화 전: charge 범위(0~10+)가 p_fbr 범위(0~1)보다 훨씬 넓어
            #           동일 가중치를 줘도 charge가 cost를 압도적으로 지배하는 문제 발생.
            # 정규화 후: 모든 항이 0~1 범위로 통일되어 가중치 = 실제 기여 비율.
            _P_FBR_MAX  = 1.0          # AI 모델 출력값 범위
            _GRAVY_MAX  = 4.5          # 아미노산 GRAVY 실험적 최대 절댓값
            _CHARGE_MAX = 10.0         # pH 7.4 기준 펩타이드 전하 실험적 최대 절댓값
            _MOTIF_MAX  = float(len(ref))  # 참조 모티프 길이 (h_score 최대값)

            p_fbr_n  = p_fbr           / _P_FBR_MAX
            gravy_n  = abs(gravy)      / _GRAVY_MAX
            charge_n = abs(charge)     / _CHARGE_MAX
            hscore_n = h_score         / (_MOTIF_MAX + 1e-9)

            cost = (w_ai * p_fbr_n) + (w_gr * gravy_n) + (w_ch * charge_n) - (w_cd * hscore_n)
            scored_pop.append((cost, p_fbr, gravy, charge, h_score, seq))
            
        scored_pop.sort(key=lambda x: x[0])
        best_individual = scored_pop[0]
        
        costs = [x[0] for x in scored_pop]
        unique_seqs = len(set([x[5] for x in scored_pop]))
        current_diversity = (unique_seqs / pop_size) * 100
        
        '''
        (메일 송신 이후 추가)
        실행시 조기수렴 문제가 확인되어, 돌연변이율을 초기값 그대로 가는 것이 아닌,
        다양성이 적어지면 변이율을 유동적으로 변화시키게끔 함.
        '''
        
        # [적응형 돌연변이 로직]
        if current_diversity < 15.0:
            current_mutation_rate = min(0.50, current_mutation_rate + 0.15) 
            status = "⚠️ 위기 (돌연변이율 상승↑)"
        else:
            current_mutation_rate = base_mutation_rate 
            status = "✅ 정상"
            
        history['gen'].append(gen + 1)
        history['best_cost'].append(best_individual[0])
        history['mean_cost'].append(np.mean(costs))
        history['p_fbr'].append(best_individual[1] * 100) 
        history['diversity'].append(current_diversity) 
        history['mutation_rate'].append(current_mutation_rate * 100)
        
        # [패치] 5세대 주기를 없애고, 매 세대마다 변이율(MutRate)까지 콘솔에 전수 출력함.
        print(f"  [Gen {gen+1:02d}] Cost: {history['best_cost'][-1]:.4f} | Div: {history['diversity'][-1]:.1f}% | MutRate: {current_mutation_rate*100:.0f}% | {status}")
        
        next_gen = [x[5] for x in scored_pop[:max(1, int(pop_size * 0.2))]]
        indel_count = 0
        while len(next_gen) < pop_size:
            p1, p2 = random.choices(scored_pop[:max(2, int(pop_size * 0.5))], k=2)
            crossover_pt = random.randint(1, max(1, min(len(p1[5]), len(p2[5])) - 1))
            child = p1[5][:crossover_pt] + p2[5][crossover_pt:]
            child = child[:ga_max_len]

            if random.random() < current_mutation_rate:
                if len(child) > 0:
                    if random.random() < indel_rate:  # Indel 변이 (삽입 또는 삭제)
                        if random.random() < 0.5 and len(child) < ga_max_len:  # 삽입
                            idx = random.randint(0, len(child))
                            child = child[:idx] + random.choice("ACDEFGHIKLMNPQRSTVWY") + child[idx:]
                            indel_count += 1
                        elif len(child) > ga_min_len:  # 삭제
                            idx = random.randint(0, len(child) - 1)
                            child = child[:idx] + child[idx+1:]
                            indel_count += 1
                        else:  # 길이 제약으로 Indel 불가 시 점 변이로 대체
                            idx = random.randint(0, len(child) - 1)
                            child = child[:idx] + random.choice("ACDEFGHIKLMNPQRSTVWY") + child[idx+1:]
                    else:  # 점 변이 (Substitution)
                        idx = random.randint(0, len(child) - 1)
                        child = child[:idx] + random.choice("ACDEFGHIKLMNPQRSTVWY") + child[idx+1:]
            next_gen.append(child)

        history['indel_count'].append(indel_count)
        pop = next_gen

        # 세대별 체크포인트 저장
        if (gen + 1) % checkpoint_interval == 0 or gen == generations - 1:
            checkpoint_data = {
                'generation': gen + 1,
                'best_seq': best_individual[5],
                'best_cost': float(best_individual[0]),
                'best_p_fbr': float(best_individual[1]),
                'best_gravy': float(best_individual[2]),
                'best_charge': float(best_individual[3]),
                'indel_count': indel_count,
                'history_snapshot': {k: [float(v) for v in vals] for k, vals in history.items()},
                'population': [x[5] for x in scored_pop]
            }
            cp_path = os.path.join(drive_path, f"ga_checkpoint_gen{gen+1:03d}.json")
            with open(cp_path, 'w', encoding='utf-8') as f:
                json.dump(checkpoint_data, f, ensure_ascii=False, indent=2)
            print(f"  💾 [Gen {gen+1:02d}] 체크포인트 저장 완료 (Indels: {indel_count}) → {cp_path}")

    # 반환값: (최종 점수 튜플, 최종 서열), 그리고 전체 역사 기록
    final_metrics = (best_individual[0], best_individual[1], best_individual[2], best_individual[3], best_individual[4])
    final_seq = best_individual[5]
    
    return (final_metrics, final_seq), history


# 진화 디버깅 그래프 출력 함수
def plot_evolution_history(ga_history):
    """
    적응형 유전 알고리즘(Adaptive GA)의 30세대 전수 연산 데이터를 기반으로
    수렴 속도, 면역 회피력, 유전자 다양성 방어 다이내믹스를 동시에 시각화합니다.
    """
    import matplotlib.pyplot as plt
    import numpy as np

    # 1. 그래프 전체 스타일 및 고해상도(DPI 300) 설정 (os 환경 반영)
    if os.name == 'nt':  # Windows 환경
        plt.rcParams['font.family'] = 'Malgun Gothic'
    elif os.name == 'posix': # Mac 환경
        plt.rcParams['font.family'] = 'AppleGothic'
    plt.rcParams['axes.unicode_minus'] = False
    
    # 3개의 핵심 그래프를 세로로 배치하는 가로 14인치, 세로 15인치의 대형 프레임 구성
    fig, axs = plt.subplots(3, 1, figsize=(14, 15), dpi=300)
    fig.suptitle(" In Silico Peptide Evolution Granular Report\n(적응형 유전 알고리즘 세대별 전수 추적 명세서)",fontsize=18, fontweight='bold', y=0.96)

    generations = ga_history['gen']

    # -------------------------------------------------------------
    # [Graph 1] 비용 함수 수렴 및 최적화 추이 (Best Cost vs Mean Cost)
    # -------------------------------------------------------------
    axs[0].plot(generations, ga_history['best_cost'], color='#d63031', marker='o', markersize=5, linewidth=2.5, label='Best Individual Cost (최고 성적 개체)')
    axs[0].plot(generations, ga_history['mean_cost'], color='#ff7675', linestyle='--', linewidth=1.5, alpha=0.7, label='Population Mean Cost (세대 평균 비용)')
    
    axs[0].set_title("1. Fitness Optimization & Convergence Curve (수학적 수렴 및 안정성 검증)", fontsize=13, fontweight='bold', pad=10)
    axs[0].set_ylabel("Total Penalty Cost Score", fontsize=11, fontweight='bold')
    axs[0].set_xticks(generations) # 모든 세대(1~30)를 X축 눈금에 강제 매핑하여 누락 방지
    axs[0].grid(True, linestyle=':', alpha=0.5)
    axs[0].legend(loc='upper right', fontsize=10)

    # -------------------------------------------------------------
    # [Graph 2] 면역 회피력 강화 및 타겟 돌파 추이 (P_FBR 궤적)
    # -------------------------------------------------------------
    axs[1].plot(generations, ga_history['p_fbr'], color='#0984e3', marker='s', markersize=5, linewidth=2.5, label='Best Individual P_FBR')
    # 교수님 보고용 지향선(Threshold) 추가
    axs[1].axhline(y=40, color='#636e72', linestyle=':', linewidth=2, label='Clinical Rejection Threshold (임상 거부 기준선: 40%)')
    axs[1].fill_between(generations, ga_history['p_fbr'], 40, where=(np.array(ga_history['p_fbr']) <= 40), 
                        color='#74b9ff', alpha=0.2, label='Safe Zone (면역 회피 성공 영역)')

    axs[1].set_title("2. Immune Evasion Trajectory: Inflammation Probability (염증 유발 확률 전수 하락 곡선)", fontsize=13, fontweight='bold', pad=10)
    axs[1].set_ylabel("Inflammation Probability (P_FBR, %)", fontsize=11, fontweight='bold')
    axs[1].set_xticks(generations)
    axs[1].set_ylim(0, max(ga_history['p_fbr']) + 10)
    axs[1].grid(True, linestyle=':', alpha=0.5)
    axs[1].legend(loc='upper right', fontsize=10)

    # -------------------------------------------------------------
    # [Graph 3] 첨부 이미지 양식: 다양성 선 그래프 + 변이율 막대 그래프 (이중 Y축 복합형)
    # -------------------------------------------------------------
    # 왼쪽 Y축: 유전자 다양성 (꺾은선 그래프)
    color_div = '#27ae60'
    axs[2].set_xlabel('Generation (진화 세대)', fontsize=11, fontweight='bold')
    axs[2].set_ylabel('Population Diversity (유전자 다양성, %)', color=color_div, fontsize=11, fontweight='bold')
    
    # 🔥 수정: line_div 변수 사용 경고 해결 및 명시적 범례 추가
    line_div = axs[2].plot(generations, ga_history['diversity'], color=color_div, marker='^', markersize=6, linewidth=2.5, label='Unique Sequence Ratio (다양성 비율)')
    
    axs[2].tick_params(axis='y', labelcolor=color_div)
    
    # 조기 수렴 경고선도 변수에 할당
    line_warn = axs[2].axhline(y=15, color='#e74c3c', linestyle='--', linewidth=1.5, alpha=0.6, label='Premature Convergence Warning (조기 수렴 경고선: 15%)')
    
    axs[2].set_ylim(0, 105)

    # 오른쪽 Y축: 시스템이 동적으로 가한 적응형 돌연변이율 (막대 그래프)
    ax2_twin = axs[2].twinx()
    color_mut = '#8e44ad'
    ax2_twin.set_ylabel('Applied Mutation Rate (적용된 돌연변이율, %)', color=color_mut, fontsize=11, fontweight='bold')
    bar_mut = ax2_twin.bar(generations, ga_history['mutation_rate'], color=color_mut, alpha=0.25, width=0.6, label='Dynamic Adaptive Mutation Rate (동적 변이 제어량)')
    ax2_twin.tick_params(axis='y', labelcolor=color_mut)
    ax2_twin.set_ylim(0, 60) # 최대 50% 폭증하는 변이율을 시각적으로 강조

    # 🔥 수정: 변수로 명시적으로 할당한 객체들을 리스트로 묶어서 하나의 범례(Legend) 상자에 깔끔하게 통합
    # axhline은 리스트로 반환되지 않는 단일 객체이고, plot과 bar는 리스트로 반환되므로 구조를 맞춰줌
    handles = line_div + [line_warn] + [bar_mut]
    labels = [h.get_label() for h in handles]
    axs[2].legend(handles, labels, loc='upper right', fontsize=10)
    
    axs[2].set_title("3. Genetic Diversity Defense via Adaptive Mutation (적응형 제어를 통한 생태계 정체 버그 해결 검증)", fontsize=13, fontweight='bold', pad=10)
    axs[2].set_xticks(generations)
    axs[2].grid(True, linestyle=':', alpha=0.5)

    # 2. 레이아웃 자동 조절 및 출력
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    
    # 3. 그래프 저장   
    try:
        figure_time = datetime.now().strftime('%y%m%d_%H%M%S')
        save_path = os.path.join(drive_path, f"In Silico peptide evolution granular report_{figure_time}.png")
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"✅ 그래프가 저장되었습니다: {save_path}")
    except Exception as e:
        print(f"⚠️ 이미지 저장 실패: {e}")
    
    plt.show()
    print("📈 [시각화 완료] 1세대부터 30세대까지의 전수 경향성 차트가 성공적으로 고해상도로 렌더링되었습니다.")

# -------------------------------------------------------------
# 8. 파이프라인 가동 및 대시보드 출력
# -------------------------------------------------------------
tracemalloc.start()
start_time = time.time()

# 메인 엔진 호출
best_results, evolution_history = run_pipeline_B(best_model, aa_idx_main, embed_layer_main, system_config)

(cost, p_fbr, gravy, charge, h_raw), best_seq = best_results

ref_len = len(system_config.get("design_constraints", {}).get("hCD47_reference", "EVTELT"))
h_pct = (h_raw / ref_len) * 100 if ref_len > 0 else 0

end_time = time.time()
_, peak_mem = tracemalloc.get_traced_memory()
tracemalloc.stop()

print("\n" + "="*65)
print("🖥️ [Final Dashboard] 통합 AI 펩타이드 설계 명세서 (Adaptive GA)")
print("="*65)
print(f"✨ [최종 역설계 서열] : {best_seq}")
print("-" * 65)
print(f"  ▶ 통합 평가 점수 (Cost) : {cost:.4f}")
print(f"  ▶ 염증 발생 확률 (P_FBR): {p_fbr * 100:.2f} %")
print(f"  ▶ 구조 상동성 (hCD47)   : {h_pct:.1f} %")
print(f"  ▶ 친소수성 (GRAVY)      : {gravy:.3f}")
print(f"  ▶ 전하량 (Charge)       : {charge:.3f}")
print("-" * 65)
print(f"  ⏱️ 소요 시간: {end_time - start_time:.2f} 초 | 💾 메모리: {peak_mem / 1024 / 1024:.2f} MB")
print("="*65)

# (선택) 시각화 리포트가 필요할 때만 그래프 출력
plot_evolution_history(evolution_history)
#%%
"""8. 민감도 분석"""

print("\n🧬 [Phase 3] Dynamic Sensitivity Analysis Started...")

def execute_sensitivity_test(model, aa_to_idx, embed_layer, base_config):
    scenarios = {
        "Baseline (Balanced)": {"w_1_ai": 1.0, "w_2_gravy": 0.5, "w_3_charge": 0.5, "w_4_cd47": 0.4},
        "Scenario A (Only Immune)": {"w_1_ai": 3.0, "w_2_gravy": 0.1, "w_3_charge": 0.1, "w_4_cd47": 0.1},
        "Scenario B (Only Physio)": {"w_1_ai": 0.2, "w_2_gravy": 3.0, "w_3_charge": 3.0, "w_4_cd47": 0.1},
        "Scenario C (Motif Obsession)": {"w_1_ai": 0.2, "w_2_gravy": 0.1, "w_3_charge": 0.1, "w_4_cd47": 3.0}
    }

    res_list = []
    model.eval()

    for s_name, weights in scenarios.items():
        print(f"▶ Testing: [{s_name}]")
        temp_config = copy.deepcopy(base_config)
        temp_config["weights"] = weights
        temp_config["algorithm_params"]["ga_generations"] = 15  # 빠른 분석

        (best_tuple, best_seq), _ = run_pipeline_B(model, aa_to_idx, embed_layer, temp_config)
        cost, p_fbr, gravy, charge, motif = best_tuple

        res_list.append({
            "Scenario": s_name,
            "P_FBR": f"{p_fbr*100:.1f}%",
            "GRAVY": round(gravy, 2),
            "Charge": round(charge, 2),
            "Motif Score": round(motif, 2),
            "Top Sequence": best_seq,
            "Cost": round(cost, 3)
        })

    return pd.DataFrame(res_list)

df_sensitivity = execute_sensitivity_test(best_model, aa_idx_main, embed_layer_main, system_config)

print("\n" + "="*85)
print("🏆 [Final Report] Sensitivity Analysis Results")
print("="*85)
print(df_sensitivity.to_string(index=False))
print("="*85)